### ISSUE TITLE
OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by Lexarymade** [hpcaitech/Open-Sora#525]
now I face following error：
OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json.
how to fix this ?

**Comment by Lexarymade** [comment]
I've download the opensora model, the vae, and the t5.
I just want to load the pre-downloaded model

**Comment by syc11-25** [comment]
same problem，by export HF_ENDPOINT=https://hf-mirror.com，sometimes works，sometimes also OSError

**Comment by zhengzangw** [comment]
> I've download the opensora model, the vae, and the t5. I just want to load the pre-downloaded model

If you downloaded in your local machine, you should modify the `config/opensora-v1-2/inference/sample.py`, including 

https://github.com/hpcaitech/Open-Sora/blob/65c61d0d5dd12a1cb7649d00caa65c2ce6600cc9/configs/opensora-v1-2/inference/sample.py#L18

https://github.com/hpcaitech/Open-Sora/blob/65c61d0d5dd12a1cb7649d00caa65c2ce6600cc9/configs/opensora-v1-2/inference/sample.py#L26

https://github.com/hpcaitech/Open-Sora/blob/65c61d0d5dd12a1cb7649d00caa65c2ce6600cc9/configs/opensora-v1-2/inference/sample.py#L33

**Comment by zhengzangw** [comment]
Otherwise, if you want the automatic downloading, just follow 

> same problem，by export HF_ENDPOINT=[https://hf-mirror.com，sometimes](https://hf-mirror.com%EF%BC%8Csometimes) works，sometimes also OSError

use

```bash
export HF_ENDPOINT=https://hf-mirror.com
```

**Comment by zhengzangw** [comment]
We've tested our inference script both in China and outside China, and both work. If after downloading it is still not working, please share your config and error, I will try to fix.

**Comment by liuxi0099** [comment]
Using export HF_ENDPOINT=https://hf-mirror.com will download 2 models:

`vae/config.json: 631B [00:00, 1.05MB/s]
diffusion_pytorch_model.safetensors: 100%|███████████████████████████████| 335M/335M [00:17<00:00, 18.9MB/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████| 2/2 [00:31<00:00, 15.61s/it]
config.json: 688B [00:00, 1.01MB/s]
model.safetensors: 100%|███████████████████████████████████████████████| 4.84G/4.84G [07:35<00:00, 10.6MB/s]`

**And a new bug occurs:**
`python3 gradio/app.py
...
TypeError: STDiT3.__init__() got an unexpected keyword argument 'force_huggingface'`

Though, I have defined the path of pre-downloaded 3 models in Open-Sora/configs/opensora-v1-2/inference/sample.py

Maybe there are some bugs when migrating from v1.1 to v1.2?

**Comment by zhengzangw** [comment]
The downloading process seems correct.

For the next problem, we have fixed it as mentioned in #507. Please try pull the lastest code and run again.

**Comment by baoblei** [comment]
> Though, I have defined the path of pre-downloaded 3 models in Open-Sora/configs/opensora-v1-2/inference/sample.py. Using export HF_ENDPOINT=https://hf-mirror.com will download 2 models:不过，我已经在 Open-Sora/configs/opensora-v1-2/inference/sample.py 中定义了预下载的 3 个模型的路径。使用export HF_ENDPOINT= https://hf-mirror.com 将下载2个模型：
> 
> ```shell
> vae/config.json: 631B [00:00, 1.05MB/s]
> diffusion_pytorch_model.safetensors: 100%|███████████████████████████████| 335M/335M [00:17<00:00, 18.9MB/s]
> Loading checkpoint shards: 100%|██████████████████████████████████████████████| 2/2 [00:31<00:00, 15.61s/it]
> config.json: 688B [00:00, 1.01MB/s]
> model.safetensors: 100%|███████████████████████████████████████████████| 4.84G/4.84G [07:35<00:00, 10.6MB/s]
> ```
> 
> **And a new bug occurs:并且出现了一个新的bug：**
> 
> ```shell
> python3 gradio/app.py 
> ...
> TypeError: STDiT3.__init__() got an unexpected keyword argument 'force_huggingface'
> ```
> 
> Maybe there are some bugs when migrating from v1.1 to v1.2?也许从 v1.1 迁移到 v1.2 时存在一些错误？

I got a similar error
TypeError: STDiT3.__init__() got an unexpected keyword argument 'qk_norm_legacy'

**Comment by XuanjiaZ** [comment]
I still face the same problem of ***"OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json."***, even if I change these three chpt path by my local ckpt path (i.e., ***hpcai-tech/OpenSora-STDiT-v3, hpcai-tech/OpenSora-VAE-v1.2, and DeepFloyd/t5-v1_1-xxl*** in sample.py).

And then, I find that "PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers" is used in line 270 of "***/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py***", where xj_opensora is my conda environment.
Thus, I download model weight "***PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers***" and change the path of line 270 by local path.

However, I meet another problem, as follows:
> File "/home/project/Open-Sora-main/scripts/inference.py", line 305, in <module>
    main()
  File "/home/project/Open-Sora-main/scripts/inference.py", line 78, in main
    vae = build_module(cfg.vae, MODELS).to(device, dtype).eval()
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/registry.py", line 24, in build_module
    return builder.build(cfg)
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py", line 298, in OpenSoraVAE_V1_2
    load_checkpoint(model, from_pretrained)
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 203, in load_checkpoint
    load_from_sharded_state_dict(model, ckpt_path, model_name, strict=strict)
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 150, in load_from_sharded_state_dict
    ckpt_io.load_model(model, os.path.join(ckpt_path, model_name), strict=strict)
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/checkpoint_io_base.py", line 85, in load_model
    index_file_exists, index_file_path = has_index_file(checkpoint)
  File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/utils.py", line 720, in has_index_file
    raise RuntimeError(f"Invalid checkpoint path {checkpoint_path}. Expected a file or a directory.")
***RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory.***

where " /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2" is my local path.

I find it is because the func load_checkpoint() in "***/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py***" set a default argument 'model_name="model"', and following will take a path "/home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model", which is not exist in huggingface model "hpcai-tech/OpenSora-VAE-v1.2/".

So, how can I fix it? @zhengzangw 

Thanks!!

**Comment by JingyuWu-ZJU** [comment]
> Though, I have defined the path of pre-downloaded 3 models in Open-Sora/configs/opensora-v1-2/inference/sample.py. Using export HF_ENDPOINT=https://hf-mirror.com will download 2 models:
> 
> ```shell
> vae/config.json: 631B [00:00, 1.05MB/s]
> diffusion_pytorch_model.safetensors: 100%|███████████████████████████████| 335M/335M [00:17<00:00, 18.9MB/s]
> Loading checkpoint shards: 100%|██████████████████████████████████████████████| 2/2 [00:31<00:00, 15.61s/it]
> config.json: 688B [00:00, 1.01MB/s]
> model.safetensors: 100%|███████████████████████████████████████████████| 4.84G/4.84G [07:35<00:00, 10.6MB/s]
> ```
> 
> **And a new bug occurs:**
> 
> ```shell
> python3 gradio/app.py 
> ...
> TypeError: STDiT3.__init__() got an unexpected keyword argument 'force_huggingface'
> ```
> 
> Maybe there are some bugs when migrating from v1.1 to v1.2?

If you want to use the model local, you also should to check the vae config.json, In the config.json of VAE, there is also a pretrained model request from vae_2d: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers, you should change this to your local path.

**Comment by XuanjiaZ** [comment]
> > Though, I have defined the path of pre-downloaded 3 models in Open-Sora/configs/opensora-v1-2/inference/sample.py. Using export HF_ENDPOINT=https://hf-mirror.com will download 2 models:
> > ```shell
> > vae/config.json: 631B [00:00, 1.05MB/s]
> > diffusion_pytorch_model.safetensors: 100%|███████████████████████████████| 335M/335M [00:17<00:00, 18.9MB/s]
> > Loading checkpoint shards: 100%|██████████████████████████████████████████████| 2/2 [00:31<00:00, 15.61s/it]
> > config.json: 688B [00:00, 1.01MB/s]
> > model.safetensors: 100%|███████████████████████████████████████████████| 4.84G/4.84G [07:35<00:00, 10.6MB/s]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **And a new bug occurs:**
> > ```shell
> > python3 gradio/app.py 
> > ...
> > TypeError: STDiT3.__init__() got an unexpected keyword argument 'force_huggingface'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe there are some bugs when migrating from v1.1 to v1.2?
> 
> If you want to use the model local, you also should to check the vae config.json, In the config.json of VAE, there is also a pretrained model request from vae_2d: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers, you should change this to your local path.
> 
> Additionally, i also find that in the path: /Open-Sora-main/opensora/models/vae/vae.py should change the path of PixArt-alpha

I have change path in the vae config.json, vae.py and sample.py, but it still happend to BUG:`RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory.`.

**Comment by zzzzzzfy** [comment]
> I still face the same problem of _**"OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json."**_, even if I change these three chpt path by my local ckpt path (i.e., _**hpcai-tech/OpenSora-STDiT-v3, hpcai-tech/OpenSora-VAE-v1.2, and DeepFloyd/t5-v1_1-xxl**_ in sample.py).
> 
> And then, I find that "PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers" is used in line 270 of "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py**_", where xj_opensora is my conda environment. Thus, I download model weight "_**PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers**_" and change the path of line 270 by local path.
> 
> However, I meet another problem, as follows:
> 
> > File "/home/project/Open-Sora-main/scripts/inference.py", line 305, in 
> > main()
> > File "/home/project/Open-Sora-main/scripts/inference.py", line 78, in main
> > vae = build_module(cfg.vae, MODELS).to(device, dtype).eval()
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/registry.py", line 24, in build_module
> > return builder.build(cfg)
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
> > return self.build_func(cfg, *args, **kwargs, registry=self)
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
> > obj = obj_cls(**args)  # type: ignore
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py", line 298, in OpenSoraVAE_V1_2
> > load_checkpoint(model, from_pretrained)
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 203, in load_checkpoint
> > load_from_sharded_state_dict(model, ckpt_path, model_name, strict=strict)
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 150, in load_from_sharded_state_dict
> > ckpt_io.load_model(model, os.path.join(ckpt_path, model_name), strict=strict)
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/checkpoint_io_base.py", line 85, in load_model
> > index_file_exists, index_file_path = has_index_file(checkpoint)
> > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/utils.py", line 720, in has_index_file
> > raise RuntimeError(f"Invalid checkpoint path {checkpoint_path}. Expected a file or a directory.")
> > _**RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory.**_
> 
> where " /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2" is my local path.
> 
> I find it is because the func load_checkpoint() in "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py**_" set a default argument 'model_name="model"', and following will take a path "/home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model", which is not exist in huggingface model "hpcai-tech/OpenSora-VAE-v1.2/".
> 
> So, how can I fix it? @zhengzangw
> 
> Thanks!!

Hello, I meet the same problem with you and I hope my solution can help:

change the vae path in sample.py to
`vae = dict(
    type="OpenSoraVAE_V1_2",
    from_pretrained="hpcai-tech/OpenSora-VAE-v1.2/model.safetensors",
    micro_frame_size=17,
    micro_batch_size=4,
)` 

perhaps the problem related to the function `load_checkpoint`  defined in ckpt.utils.py, which doesn't match well with the path in sample.py

**Comment by XuanjiaZ** [comment]
> > I still face the same problem of _**"OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json."**_, even if I change these three chpt path by my local ckpt path (i.e., _**hpcai-tech/OpenSora-STDiT-v3, hpcai-tech/OpenSora-VAE-v1.2, and DeepFloyd/t5-v1_1-xxl**_ in sample.py).
> > And then, I find that "PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers" is used in line 270 of "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py**_", where xj_opensora is my conda environment. Thus, I download model weight "_**PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers**_" and change the path of line 270 by local path.
> > However, I meet another problem, as follows:
> > > File "/home/project/Open-Sora-main/scripts/inference.py", line 305, in
> > > main()
> > > File "/home/project/Open-Sora-main/scripts/inference.py", line 78, in main
> > > vae = build_module(cfg.vae, MODELS).to(device, dtype).eval()
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/registry.py", line 24, in build_module
> > > return builder.build(cfg)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
> > > return self.build_func(cfg, *args, **kwargs, registry=self)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
> > > obj = obj_cls(**args)  # type: ignore
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py", line 298, in OpenSoraVAE_V1_2
> > > load_checkpoint(model, from_pretrained)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 203, in load_checkpoint
> > > load_from_sharded_state_dict(model, ckpt_path, model_name, strict=strict)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 150, in load_from_sharded_state_dict
> > > ckpt_io.load_model(model, os.path.join(ckpt_path, model_name), strict=strict)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/checkpoint_io_base.py", line 85, in load_model
> > > index_file_exists, index_file_path = has_index_file(checkpoint)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/utils.py", line 720, in has_index_file
> > > raise RuntimeError(f"Invalid checkpoint path {checkpoint_path}. Expected a file or a directory.")
> > > _**RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory.**_
> > 
> > 
> > where " /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2" is my local path.
> > I find it is because the func load_checkpoint() in "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py**_" set a default argument 'model_name="model"', and following will take a path "/home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model", which is not exist in huggingface model "hpcai-tech/OpenSora-VAE-v1.2/".
> > So, how can I fix it? @zhengzangw
> > Thanks!!
> 
> Hello, I meet the same problem with you and I hope my solution can help:
> 
> change the vae path in sample.py to
> 
> ```
> vae = dict(
>     type="OpenSoraVAE_V1_2",
>     from_pretrained="hpcai-tech/OpenSora-VAE-v1.2/model.safetensors",
>     micro_frame_size=17,
>     micro_batch_size=4,
> )
> ```
> 
> perhaps the problem is related to the function `load_checkpoint` defined in ckpt.utils.py, which doesn't match well with the path in sample.py

Thank you for you suggestion, but I still meet "RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory."😭

**Comment by XuanjiaZ** [comment]
> > I still face the same problem of _**"OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json."**_, even if I change these three chpt path by my local ckpt path (i.e., _**hpcai-tech/OpenSora-STDiT-v3, hpcai-tech/OpenSora-VAE-v1.2, and DeepFloyd/t5-v1_1-xxl**_ in sample.py).
> > And then, I find that "PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers" is used in line 270 of "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py**_", where xj_opensora is my conda environment. Thus, I download model weight "_**PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers**_" and change the path of line 270 by local path.
> > However, I meet another problem, as follows:
> > > File "/home/project/Open-Sora-main/scripts/inference.py", line 305, in
> > > main()
> > > File "/home/project/Open-Sora-main/scripts/inference.py", line 78, in main
> > > vae = build_module(cfg.vae, MODELS).to(device, dtype).eval()
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/registry.py", line 24, in build_module
> > > return builder.build(cfg)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
> > > return self.build_func(cfg, *args, **kwargs, registry=self)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
> > > obj = obj_cls(**args)  # type: ignore
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py", line 298, in OpenSoraVAE_V1_2
> > > load_checkpoint(model, from_pretrained)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 203, in load_checkpoint
> > > load_from_sharded_state_dict(model, ckpt_path, model_name, strict=strict)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 150, in load_from_sharded_state_dict
> > > ckpt_io.load_model(model, os.path.join(ckpt_path, model_name), strict=strict)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/checkpoint_io_base.py", line 85, in load_model
> > > index_file_exists, index_file_path = has_index_file(checkpoint)
> > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/utils.py", line 720, in has_index_file
> > > raise RuntimeError(f"Invalid checkpoint path {checkpoint_path}. Expected a file or a directory.")
> > > _**RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory.**_
> > 
> > 
> > where " /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2" is my local path.
> > I find it is because the func load_checkpoint() in "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py**_" set a default argument 'model_name="model"', and following will take a path "/home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model", which is not exist in huggingface model "hpcai-tech/OpenSora-VAE-v1.2/".
> > So, how can I fix it? @zhengzangw
> > Thanks!!
> 
> Hello, I meet the same problem with you and I hope my solution can help:
> 
> change the vae path in sample.py to
> 
> ```
> vae = dict(
>     type="OpenSoraVAE_V1_2",
>     from_pretrained="hpcai-tech/OpenSora-VAE-v1.2/model.safetensors",
>     micro_frame_size=17,
>     micro_batch_size=4,
> )
> ```
> 
> perhaps the problem is related to the function `load_checkpoint` defined in ckpt.utils.py, which doesn't match well with the path in sample.py

Thank you for your suggestion, but I still meet "RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory."😭

**Comment by Crd1140234468** [comment]
> > > I still face the same problem of _**"OSError: PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers does not appear to have a file named config.json."**_, even if I change these three chpt path by my local ckpt path (i.e., _**hpcai-tech/OpenSora-STDiT-v3, hpcai-tech/OpenSora-VAE-v1.2, and DeepFloyd/t5-v1_1-xxl**_ in sample.py).
> > > And then, I find that "PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers" is used in line 270 of "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py**_", where xj_opensora is my conda environment. Thus, I download model weight "_**PixArt-alpha/pixart_sigma_sdxlvae_T5_diffusers**_" and change the path of line 270 by local path.
> > > However, I meet another problem, as follows:
> > > > File "/home/project/Open-Sora-main/scripts/inference.py", line 305, in
> > > > main()
> > > > File "/home/project/Open-Sora-main/scripts/inference.py", line 78, in main
> > > > vae = build_module(cfg.vae, MODELS).to(device, dtype).eval()
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/registry.py", line 24, in build_module
> > > > return builder.build(cfg)
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
> > > > return self.build_func(cfg, *args, **kwargs, registry=self)
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
> > > > obj = obj_cls(**args)  # type: ignore
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/models/vae/vae.py", line 298, in OpenSoraVAE_V1_2
> > > > load_checkpoint(model, from_pretrained)
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 203, in load_checkpoint
> > > > load_from_sharded_state_dict(model, ckpt_path, model_name, strict=strict)
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py", line 150, in load_from_sharded_state_dict
> > > > ckpt_io.load_model(model, os.path.join(ckpt_path, model_name), strict=strict)
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/checkpoint_io_base.py", line 85, in load_model
> > > > index_file_exists, index_file_path = has_index_file(checkpoint)
> > > > File "/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/colossalai/checkpoint_io/utils.py", line 720, in has_index_file
> > > > raise RuntimeError(f"Invalid checkpoint path {checkpoint_path}. Expected a file or a directory.")
> > > > _**RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory.**_
> > > 
> > > 
> > > where " /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2" is my local path.
> > > I find it is because the func load_checkpoint() in "_**/home/anaconda3/envs/xj_opensora/lib/python3.9/site-packages/opensora/utils/ckpt_utils.py**_" set a default argument 'model_name="model"', and following will take a path "/home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model", which is not exist in huggingface model "hpcai-tech/OpenSora-VAE-v1.2/".
> > > So, how can I fix it? @zhengzangw
> > > Thanks!!
> > 
> > 
> > Hello, I meet the same problem with you and I hope my solution can help:
> > change the vae path in sample.py to
> > ```
> > vae = dict(
> >     type="OpenSoraVAE_V1_2",
> >     from_pretrained="hpcai-tech/OpenSora-VAE-v1.2/model.safetensors",
> >     micro_frame_size=17,
> >     micro_batch_size=4,
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > perhaps the problem is related to the function `load_checkpoint` defined in ckpt.utils.py, which doesn't match well with the path in sample.py
> 
> Thank you for your suggestion, but I still meet "RuntimeError: Invalid checkpoint path /home/project/hugmodel/hpcai-tech__OpenSora-VAE-v1.2/model. Expected a file or a directory."😭
修改ckpt_utils.py 190行：
`def load_checkpoint(model, ckpt_path, save_as_pt=False, model_name="model.safetensors", strict=False):`
