### ISSUE TITLE
Unexpected Key Error when using 768x768 text-to-video with ColossalAI SP

### ISSUE THREAD

**Issue by dufengfeng** [hpcaitech/Open-Sora#859]
First of all, thank you so much for your amazing work on OpenSora 2.0 — it's an impressive and inspiring contribution to the open-source video generation community.

I’ve been testing the text-to-video pipeline, and I noticed that: With 256×256 resolution, everything runs smoothly on my setup. However, when I try 768×768 resolution using colossalai sequence parallelism (SP) in a multi-GPU setting, I encounter the following error during runtime: _flash_attn_forward() got an unexpected keyword argument 'window_size_left'

My current flash-attn version is 2.6.3. Do you have any suggestions?

**Comment by dufengfeng** [comment]
Thank you for the clarification! I have uninstalled the existing version and reinstalled Flash Attention v2 from the fd2fc9d85c8e54e5c20436465bca709bc1a6c5a1 branch as you suggested. It works perfectly now.
Really appreciate your help!
