### ISSUE TITLE
Error when using 768x768 text-to-video with ColossalAI SP: _flash_attn_forward() got an unexpected keyword argument 'window_size_left'

### ISSUE THREAD

**Issue by dufengfeng** [hpcaitech/Open-Sora#858]
First of all, thank you so much for your amazing work on OpenSora 2.0 — it's an impressive and inspiring contribution to the open-source video generation community. I’ve been testing the text-to-video pipeline, and I noticed that:With 256×256 resolution, everything runs smoothly on my setup.

However, when I try 768×768 resolution using ColossalAI sequence parallelism (SP) in a multi-GPU setting, I encounter the following error during runtime:

bash
复制
编辑
_flash_attn_forward() got an unexpected keyword argument 'window_size_left'
My current flash-attn version is 2.6.3.

Do you have any suggestions?

**Comment by fjyu95** [comment]
I have also encountered the same problem. Have you solved it?
my devices is H20*4，torch: 2.4.0+cu121，flash_attn: 2.6.3，only run 768×768 resolution got 'window_size_left' error.
